name: CI

on:
  push:
    branches: [master, trunk]
  pull_request:

jobs:
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          components: rustfmt
          override: true
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
  build:
    name: Check that the code builds
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
  examples:
    name: Check that examples build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --example animation
    # Will exhibit linker warnings for 10.13 and below, expected:
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --example autolayout
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --example calculator
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --example custom_image_drawing
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --example defaults
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --example frame_layout
    # fails because it needs uikit, which is not
    # building for me
    #- uses: actions-rs/cargo@v1
    #  with:
    #    command: build
    #    args: --example ios-beta
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --example text_input
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --example todos_list
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --example window
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --example window_controller
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --example window_delegate
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --features webview --example webview_custom_protocol
